### PR TITLE
fix nil pointer panic

### LINKED ISSUE #689: nil pointer panic happens in updateClusterTaints()
#### What happened:
run clusternet-controller-manager built from main  happens paic, the error log as bellow
image
  
acctually, this failure is indruced from PR #673

#### What you expected to happen:

updateClusterTaints()  will run normally when managed cluster's status is true or the managed cluster is  a new cluster

#### How to reproduce it (as minimally and precisely as possible):
build  image with PR #673, and run clusternet-controller-manager

### PR DESCRIPTION
**Pull request by willzgli**
#### Which issue(s) this PR fixes:

Fixes #689

### CODE REVIEW

File: pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go [hunk 1]
```diff
@@ -231,7 +234,7 @@ func (c *Controller) updateClusterTaints(ctx context.Context, cluster *clusterap
 func patchClusterTaints(ctx context.Context, client clusternetclientset.Interface, cluster *clusterapi.ManagedCluster,
 	taintsToAdd, taintsToRemove []*corev1.Taint) error {
 	var err error
-	var newCluster *clusterapi.ManagedCluster
+	var newCluster *clusterapi.ManagedCluster = cluster
```
Comment (dixudx) [inline pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:237]: This is not needed. And we'd better not do this, since `cluster` is a pointer, we may modify `newCluster` inadvertently.

File: pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go [hunk 2]
```diff
@@ -191,6 +191,9 @@ func (c *Controller) updateClusterCondition(ctx context.Context, cluster *cluste
 }
 
 func (c *Controller) updateClusterTaints(ctx context.Context, cluster *clusterapi.ManagedCluster) error {
+	if cluster == nil {
```
Comment (dixudx) [inline pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:194]: Could we modify L177 to return non-nil `*clusterapi.ManagedCluster`? If so, we don't need to check whether `cluster` is nil or not?

Comment (dixudx) [reply pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:194]: Also please check `if len(cluster.Status.Conditions) > 0`.

File: pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go (hunk 1 above)
Comment (dixudx) [reply pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:237]: Actually, at least one of `RemoveTaint` and `AddOrUpdateTaint` will be performed. https://github.com/clusternet/clusternet/blob/main/pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go#L222-L225

File: pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go (hunk 2 above)
Comment (dixudx) [reply pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:194]: > I modify L177 firstly, but I considered later that if currentReadyCondition is equal with observedReadyCondition or observedReadyCondition is nil, updateClusterTaints dosn't neet to run, so I add a judgement here.

This will make this piece of codes confusing, especially without any comments. Also this will make it harder to add further changes.

I'd prefer to leave that to `updateClusterTaints`.

Comment (dixudx) [reply pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:194]: > len(cluster.Status.Conditions) will never be 0, because it is updated at
https://github.com/clusternet/clusternet/blob/main/pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go#L188-L189

NO!

It may return from here https://github.com/clusternet/clusternet/blob/main/pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go#L176-L178.

File: pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go (hunk 1 above)
Comment (willzgli) [reply pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:237]: yes, if RemoveTaint isn't be performed,  the newCluster is nil, and AddOrUpdateTaint will recieve a nil, then a panic happens in AddOrUpdateTaint

Comment (dixudx) [reply pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:237]: Ok, got it. You're right. Nice catch.

Let's use 
```go
newCluster := cluster.DeepCopy()
```

File: pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go (hunk 2 above)
Comment (willzgli) [reply pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:194]: > > I modify L177 firstly, but I considered later that if currentReadyCondition is equal with observedReadyCondition or observedReadyCondition is nil, updateClusterTaints dosn't neet to run, so I add a judgement here.
> 
> This will make this piece of codes confusing, especially without any comments. Also this will make it harder to add further changes.
> 
> I'd prefer to leave that to `updateClusterTaints`.

ok, move it to L177

Comment (willzgli) [reply pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:194]: > > len(cluster.Status.Conditions) will never be 0, because it is updated at
> > https://github.com/clusternet/clusternet/blob/main/pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go#L188-L189
> 
> NO!
> 
> It may return from here https://github.com/clusternet/clusternet/blob/main/pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go#L176-L178.

cluster.Status.Conditions is nil dosen't impact "for range",  please ref: https://thanhtungvo.medium.com/golang-can-iterating-loop-for-nil-slice-ff0727911f54

File: pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go (hunk 1 above)
Comment (willzgli) [reply pkg/controllers/clusters/clusterlifecycle/clusterlifecycle_controller.go:234]: There is a cluster.DeepCopy() in AddOrUpdateTaint

**Review by dixudx — APPROVED** [review]
Good work. Thanks for the fix.
