### PR TITLE
move owned-by-description label as annotation

### LINKED ISSUE #325: Application deployment failed due to labels length limit
https://github.com/clusternet/clusternet/blob/be9a89ab08d4368f15e77d5170a89bb27653f04a/pkg/utils/deployer.go#L328

It's fine if set in annotations, and it's as expected

### PR DESCRIPTION
**Pull request by silenceper**
#### What type of PR is this?
Because labels value have a length limit, move the labels field `apps.clusternet.io/owned-by-description` into annotations

#### What this PR does / why we need it:

```
reason: 'ConfigMap "agent--train-05101029-hc-13z" is invalid: metadata.labels: Invalid
    value: "clusternet-9rkxk.agent--train-05101029-hc-13z-n2hsxsj66k2r-generic": must
    be no more than 63 characters'
```

#### Which issue(s) this PR fixes:

Fixes #325

### CODE REVIEW

File: pkg/agent/deployer/generic/generic.go [hunk 1]
```diff
@@ -179,7 +179,7 @@ func (deployer *Deployer) handleResource(ownedByValue string) error {
 	// get description ns and name
 	parts := strings.Split(ownedByValue, ".")
 	if len(parts) < 2 {
-		return fmt.Errorf("unexpected value for label %s: %s", known.ObjectOwnedByDescriptionLabel, ownedByValue)
+		return fmt.Errorf("unexpected value for label %s: %s", known.ObjectOwnedByDescriptionAnnotation, ownedByValue)
```
Comment (dixudx) [inline pkg/agent/deployer/generic/generic.go:182]: s/label/annotation

**Comment by dixudx** [comment]
cc @lmxia

**Review by dixudx — APPROVED** [review]
