### PR TITLE
reuse app deployer credentials to collect cluster status when available

### LINKED ISSUE #99: clusternet-agent sa need clusterrole permission
#### What happened:

`clusternet-agent` error log:

```
W0901 02:45:02.131938       1 status_manager.go:124] cluster status is not ready, will retry later
W0901 02:45:02.649602       1 status_manager.go:124] cluster status is not ready, will retry later
W0901 02:45:05.366810       1 status_manager.go:124] cluster status is not ready, will retry later
I0901 02:45:10.403261       1 reflector.go:255] Listing and watching *v1.Node from pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167
E0901 02:45:10.404607       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:clusternet-system:clusternet-agent" cannot list resource "nodes" in API group "" at the cluster scope
W0901 02:45:19.086087       1 status_manager.go:124] cluster status is not ready, will retry later
```

The [clusternet-agent sa](https://github.com/clusternet/clusternet/blob/main/deploy/agent/clusternet_agent_rbac.yaml#L23) need  clusterrole permission.

### PR DESCRIPTION
**Pull request by chenkaiyue**
#### What type of PR is this?
kind/bug

#### What this PR does / why we need it:
`StatusManager` reuses ServiceAccount `clusternet-app-deployer` when available to collect cluster status. If not, then it falls back to use legacy in-cluster `kubeClient`.

#### Which issue(s) this PR fixes:

Fixes #99

### CODE REVIEW

File: pkg/agent/agent.go [hunk 1]
```diff
@@ -406,3 +411,45 @@ func generateClusterName(clusterName, clusterNamePrefix string) string {
 	}
 	return clusterName
 }
+
+func getDeployerCredentials(ctx context.Context, kubeClient kubernetes.Interface) *corev1.Secret {
```
Comment (dixudx) [inline pkg/agent/agent.go:415]: try to reuse existing function or refactor.

File: pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go [hunk 2]
```diff
@@ -46,38 +46,40 @@ const (
...
-	apiserverURL     string
-	appPusherEnabled bool
-	useSocket        bool
-	parentAPIServer  string
-	nodeLister       corev1Lister.NodeLister
-	podLister        corev1Lister.PodLister
-	nodeListerSynced cache.InformerSynced
-	podListerSynced  cache.InformerSynced
+	kubeClient              kubernetes.Interface
+	clusterStatusKubeClient kubernetes.Interface
```
Comment (dixudx) [inline pkg/controllers/clusters/clusterstatus/clusterstatus_controller.go:50]: why adding an extra kubeclient? reuse `kubeClient` initialized with deployer credentials ?

**Review by dixudx — CHANGES_REQUESTED** [review]
Also considering falling back to use original `kubeClient` if deployer sa is not found

**Review by dixudx — CHANGES_REQUESTED** [review]

File: pkg/agent/constant.go [hunk 3]
```diff
@@ -71,4 +71,5 @@ const (
 const (
 	DefaultLeaseDuration = 60 * time.Second
 	DefaultRenewDeadline = 15 * time.Second
+	DefaultRetryPeriod   = 5 * time.Second
```
Comment (dixudx) [inline pkg/agent/constant.go:74]: pkg/known/constant.go has defined a `DefaultRetryPeriod`

File: pkg/agent/status_manager.go [hunk 4]
```diff
@@ -46,10 +48,26 @@ type Manager struct {
 }
 
 func NewStatusManager(ctx context.Context, apiserverURL string, regOpts *ClusterRegistrationOptions, kubeClient kubernetes.Interface) *Manager {
+	var clusterStatusClient kubernetes.Interface
+
+	timeCtx, timeCancel := context.WithTimeout(ctx, DefaultRetryPeriod)
+	defer timeCancel()
+
+	clusterStatusClient = kubeClient
```
Comment (dixudx) [inline pkg/agent/status_manager.go:56]: `clusterStatusClient := kubeClient`

or just reuse variable `kubeClient` ?

File: pkg/agent/status_manager.go [hunk 5]
```diff
@@ -46,10 +48,26 @@ type Manager struct {
 }
 
 func NewStatusManager(ctx context.Context, apiserverURL string, regOpts *ClusterRegistrationOptions, kubeClient kubernetes.Interface) *Manager {
+	var clusterStatusClient kubernetes.Interface
+
+	timeCtx, timeCancel := context.WithTimeout(ctx, DefaultRetryPeriod)
```
Comment (dixudx) [inline pkg/agent/status_manager.go:53]: s/timeCtx/retryCtx

**Review by dixudx — APPROVED** [review]
