### PR TITLE
fix con not get the correct status of the old subscription object

### LINKED ISSUE #549: we can not get the correct status of the old subscription object
#### What happened:
when we use subscription controller to watch some subscripiton object,  we found,  the status of the old object is the same as the status of the new object.

#### What you expected to happen:
we hope, get the old status of the old object from indexer. 
And we found the question code is this line https://github.com/clusternet/clusternet/blob/main/pkg/controllers/apps/aggregatestatus/aggregatestatus.go#L297

企业微信20221130-132747@2x

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by zhenkuang**
#### What this PR does / why we need it:
fix con not get the correct status of the old subscription object

#### Which issue(s) this PR fixes:

Fixes #549

### CODE REVIEW

File: pkg/controllers/apps/aggregatestatus/aggregatestatus.go [hunk 1]
```diff
@@ -292,6 +292,7 @@ func (c *Controller) updateSubscriptionStatus(sub *appsapi.Subscription, status
 	// Or create a copy manually for better performance
 
 	klog.V(5).Infof("try to update Subscription %q status", sub.Name)
+	sub = sub.DeepCopy()
```
Comment (dixudx) [inline pkg/controllers/apps/aggregatestatus/aggregatestatus.go:295]: Here `sub` is a pointer. Better use another object instead of `sub`.

**Review by dixudx — CHANGES_REQUESTED** [review]
Thanks for the contribution.

File: pkg/controllers/apps/aggregatestatus/aggregatestatus.go (hunk 1 above)
Comment (zhenkuang) [reply pkg/controllers/apps/aggregatestatus/aggregatestatus.go]: ok, I choose another object and commit
