### PR TITLE
fix panic when the length of bindingClusters and replicas in subscription are not equal

### LINKED ISSUE #746: controller-manager will panic when the length of bindingClusters and replicas in subscription are not equal
#### What happened:

controller-manager will panic when the length of bindingClusters and replicas in subscription are not equal

#### What you expected to happen:

do not panic

#### How to reproduce it (as minimally and precisely as possible):

when the length of bindingClusters and replicas in subscription are not equal

### PR DESCRIPTION
**Pull request by abstractmj**
#### Which issue(s) this PR fixes:

Fixes #746

### CODE REVIEW

File: pkg/controllermanager/deployer/deployer.go [hunk 1]
```diff
@@ -570,7 +570,7 @@ func (deployer *Deployer) populateLocalizations(sub *appsapi.Subscription, base
 				continue
 			}
 
-			if len(replicas) < clusterIndex {
+			if len(replicas) <= clusterIndex {
```
Comment (dixudx) [inline pkg/controllermanager/deployer/deployer.go:573]: This index starts from 0. Thus it should be `<` here.

Comment (abstractmj) [reply pkg/controllermanager/deployer/deployer.go:573]: supposing bindingClusters are cluster0, cluster1, cluster2, cluster3, and replicas are [1, 1, 1], when clusterIndex is 3, the following code will panic in "replicas[clusterIndex]"

```golang
loc.Spec.Overrides = []appsapi.OverrideConfig{
				{
					Name:  "dividing scheduling replicas",
					Value: fmt.Sprintf(`[{"path":%q,"value":%d,"op":"replace"}]`, feedOrder.ReplicaJsonPath, replicas[clusterIndex]),
					Type:  appsapi.JSONPatchType,
				},
			}
```

Comment (dixudx) [reply pkg/controllermanager/deployer/deployer.go:573]: > supposing `bindingClusters` are cluster0, cluster1, cluster2, cluster3, and replicas are [1, 1, 1]

Here the length of `bindingClusters` and replicas should be equal. And they are supposed to be equal. Would you share some clues on this? Thanks.

The current fix will bring panic as well. If `len(bindingClusters)=4`  and `len(replicas)=3`, then `len(replicas) <= 3 (the last cluster index)`, this leads to panic for `replicas[3]`.

Comment (abstractmj) [reply pkg/controllermanager/deployer/deployer.go:573]: If len(bindingClusters)=4 and len(replicas)=3, then len(replicas) <= 3 (the last cluster index), it will not go to the code "replicas[3]" and continue to process the next feed

Comment (abstractmj) [reply pkg/controllermanager/deployer/deployer.go:573]: Normally, the two are not equal, but when the scheduler is abnormal, it will cause the entire system to be unavailable, so protection should be done here.

Comment (dixudx) [reply pkg/controllermanager/deployer/deployer.go:573]: I got it. Nice catch.

This is a warning logic. So it is fine to have `<=` here.

**Review by dixudx — APPROVED** [review]
Normally the length of `bindingClusters` and `replicas` are supposed to be equal.

For third-party scheduling plugins that are not well implemented, it is good to add this PR for panic saving. Having `<=` here does not bring anything changed, it is no harm, just some warnings.
