### PR TITLE
fix pruning obsolete feeds when running in pull mode

### LINKED ISSUE #710: obsolete feeds will not be pruned in child clusters when running as pull mode
#### What happened:

When there are multiple feeds in a sub, obsolete feeds will not be pruned in child clusters when running as pull mode.

#### What you expected to happen:

hub clean the underlying object correctly

### PR DESCRIPTION
**Pull request by abstractmj**
#### What type of PR is this?
kind/bug

fix feed leak when agent is in pull mode

#### What this PR does / why we need it:

* feed may leak when agent is in pull mode
* there is no warning or error log when hub failed to prune feeds for description

#### Which issue(s) this PR fixes:

Fixes #710

### CODE REVIEW

File: pkg/agent/deployer/deployer.go [hunk 1]
```diff
@@ -94,10 +94,11 @@ func (d *Deployer) Run(
 
 	// make sure deployer gets initialized before we go next
 	appDeployerSecret := utils.GetDeployerCredentials(ctx, childKubeClientSet, d.systemNamespace, d.saTokenAutoGen)
-	if d.appPusherEnabled && d.syncMode != clusterapi.Pull {
-		klog.V(4).Infof("initializing deployer with sync mode %s", d.syncMode)
-		createDeployerCredentialsToParentCluster(ctx, parentClientSet, string(*clusterID), *dedicatedNamespace, d.childAPIServerURL, appDeployerSecret)
-	}
+
+	// creating credentials to parent cluster is also required in the pull mode,
+	// because the cleaning of redundant objects in the description is performed in the hub
```
Comment (dixudx) [inline pkg/agent/deployer/deployer.go:99]: s/hub/clusternet-controller-manager

**Review by dixudx — COMMENTED** [review]
Nice catch. Good work.

**Review by dixudx — APPROVED** [review]
