### PR TITLE
ignore checking AppPusher for helm charts

### LINKED ISSUE #735: HelmChart type resources cannot be deployed when clusternet-agent sets AppPusher=false
#### What happened:
I have a child cluster and cluster-agent is started in Dual mode with AppPusher=false, then pull mode is used for application deployment. 
```
        - --cluster-sync-mode=Dual
        - --feature-gates=SocketConnection=true,AppPusher=false,Recovery=true,Predictor=true
```

and i found Generic resources can be deployed normally, but HelmChart type resources cannot be synchronized.

#### What you expected to happen:
When the child cluster uses pull mode, HelmChart type resources can be deployed normally.

#### How to reproduce it (as minimally and precisely as possible):
sub resource is as follows:
```sub.yaml
apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
metadata:
  name: test
  namespace: test
spec:
  clusterTolerations:
  - operator: Exists
  feeds:
  - apiVersion: clusters.clusternet.io/v1beta1
    kind: HelmChart
    name: test
    namespace: foo
  schedulerName: default
  schedulingStrategy: Replication
  subscribers:
  - clusterAffinity: {}
```

The description and HelmRelease are automatically generated by the deployer.

#### Anything else we need to know?:
Upon examining the code, it was found that if AppPusher is set to false, the HelmRelease will not be updated. This causes the cluster-agent to be unable to watch for changes in HelmChart, and thus no updates are made.

This issue is caused by improper handling in the handleDescription function of the controller. The code can be found [here](https://github.com/clusternet/clusternet/blob/5247e9fcf79bbb481e4ed9a48e265ebccc810194/pkg/controllermanager/deployer/helm/helm.go#L239C2-L239C2).
Why there is such a limitation here, and can this limitation be lifted?
```
	if !*mcls[0].Status.AppPusher {
		deployer.recorder.Event(descCopy, corev1.EventTypeNormal, "", "target cluster has disabled AppPusher")
		klog.V(5).Infof("ManagedCluster with uid=%s has disabled AppPusher", mcls[0].UID)
		return nil
	}

	if err = deployer.populateHelmRelease(descCopy); err != nil {
		return err
	}
```

#### Environment:
- Clusternet version: master

### PR DESCRIPTION
**Pull request by cumirror**
#### What type of PR is this?
bugfix

#### What this PR does / why we need it:
bugfix for HelmChart resources deployment when clusternet-agent sets AppPusher=false

#### Which issue(s) this PR fixes:
Fixes #735

### CODE REVIEW

File: pkg/controllermanager/deployer/helm/helm.go [hunk 1]
```diff
@@ -232,15 +231,6 @@ func (deployer *Deployer) handleDescription(descCopy *appsapi.Description) error
 			fmt.Sprintf("can not find a ManagedCluster with uid=%s in current namespace", descCopy.Labels[known.ClusterIDLabel]))
 		return fmt.Errorf("failed to find a ManagedCluster declaration in namespace %s", descCopy.Namespace)
 	}
-	if mcls[0].Status.AppPusher == nil {
```
Comment (dixudx) [inline pkg/controllermanager/deployer/helm/helm.go:235]: If so, there is no need to list ManageClusters. Please remove it as well.

Comment (cumirror) [reply pkg/controllermanager/deployer/helm/helm.go:235]: done.

**Review by dixudx — APPROVED** [review]
